variables:
  - name: isMain
    value: $[eq(variables['Build.SourceBranch'], 'refs/heads/master')]
  - name: ServiceInfo.ReleaseVersion
    value: $(Build.BuildNumber)     
  - name: DockerHubRepositoryName
    value: bobby1072/hetzner-container-management
  - name: DockerEngineApiSettings.UnixDomainSocketEndPoint
    value: /var/run/docker.sock
  - name: DockerEngineApiSettings.UseTestHttpEndPoint
    value: "false"
  - name: ApiKey.0
    value: ""
trigger:
  branches:
    include:
      - master

name: $(Date:yy).$(Month)$(DayOfYear).$(Rev:r)

pr:
  branches:
    include:
      - "master"
      - "feature/*"
      - "hotfix/*"
      - "bugfix/*"

pool:
  vmImage: "ubuntu-latest"


stages:
  - stage: Build
    jobs:
      - job: build_backend
        displayName: "Build web api"
        steps:
          - checkout: self
            submodules: recursive

          - task: UseDotNet@2
            displayName: "Install .NET SDK"
            inputs:
              packageType: "sdk"
              version: "10.0.x"

          - task: DotNetCoreCLI@2
            displayName: "Run .NET Unit Tests"
            inputs:
              command: "test"
              projects: "src/Hetzner.Container.Management/Hetzner.Container.Management.slnx"
              arguments: "-c Release"

  - stage: Publish
    condition: and(eq(variables.isMain, true), succeeded())
    jobs:
      - job: push_api_image
        steps:
          - checkout: self
            submodules: recursive

          - task: FileTransform@2
            displayName: "Transform all configuration files"
            inputs:
              folderPath: "$(Build.SourcesDirectory)/src"
              enableXmlTransform: false
              fileType: "json"
              jsonTargetFiles: |
                Hetzner.Container.Management/Hetzner.Container.Management.Api/appsettings.json

          - task: Docker@2
            displayName: Login to Docker Hub
            inputs:
              command: login
              containerRegistry: DockerHub
              username: $(dockerHubUsername)
              password: $(dockerHubPassword)
              
          - task: Docker@2
            displayName: Build Api Image
            inputs:
              command: build
              repository: $(DockerHubRepositoryName)
              tags: |
                latest
                $(Build.BuildNumber)
              Dockerfile: "$(Build.SourcesDirectory)/src/Hetzner.Container.Management/dockerfile.api"
              buildContext: "$(Build.SourcesDirectory)"         

          - task: Docker@2
            displayName: Push Api Image
            inputs:
              command: push
              repository: $(DockerHubRepositoryName)
              tags: |
                latest
                $(Build.BuildNumber)             
